theme: jekyll-theme-minimal
title: Crusade AI
description: Text-based adventure on Solana.
title_image: "https://www.creativefabrica.com/wp-content/uploads/2022/08/31/shield-logo-template-Graphics-37440159-1.jpg"
